(defun akirak/close-window-or-workspace ()
  (interactive)
  (cond ((> (list-length (window-list)) 1)
         (delete-window))
        ((> (list-length (eyebrowse--get 'window-configs)) 1)
         (eyebrowse-close-window-config))
        ((y-or-n-p "This is the last workspace. Close the perspective? ")
         (spacemacs/layouts-ts-close))))

(defun akirak/move-current-window-to-new-workspace ()
  (interactive)
  (if (= 1 (length (window-list)))
      (message "already the last window")
    (let ((eyebrowse-new-workspace (buffer-name)))
      (delete-window)
      (eyebrowse-create-window-config)
      (message "Moved the current window to a new workspace"))))
